/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE */;
/*!40101 SET SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES */;
/*!40103 SET SQL_NOTES='ON' */;


CREATE DATABASE `conexaobd` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `conexaobd`;
CREATE TABLE `cliente` (
  `cli_cod` int(11) NOT NULL AUTO_INCREMENT,
  `cli_nome` varchar(255) DEFAULT NULL,
  `cli_tel` int(11) DEFAULT NULL,
  PRIMARY KEY (`cli_cod`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=latin1;
INSERT INTO `cliente` VALUES (15,'Nathalia de Oliveira Mendes',58336819);
INSERT INTO `cliente` VALUES (17,'Raul Lima',58999719);
INSERT INTO `cliente` VALUES (18,'joselito',12233445);
INSERT INTO `cliente` VALUES (19,'adasdas',34343);

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
